---
# https://www.tecmint.com/install-oracle-database-12c-on-centos-7/
# https://valehagayev.wordpress.com/2016/09/08/oracle-12-1-0-2-silent-install-and-de-installation-on-oel/

- name: Oracle 12c required packages
  yum: 
    name:  "{{ packages }}"
  vars:
    packages:
    - binutils.x86_64
    - compat-libcap1.x86_64
    - gcc.x86_64
    - gcc-c++.x86_64
    - glibc.i686
    - glibc.x86_64
    - glibc-devel.i686
    - glibc-devel.x86_64
    - ksh
    - compat-libstdc++-33
    - libaio.i686
    - libaio.x86_64
    - libaio-devel.i686
    - libaio-devel.x86_64
    - libgcc.i686
    - libgcc.x86_64
    - libstdc++.i686
    - libstdc++.x86_64
    - libstdc++-devel.i686
    - libstdc++-devel.x86_64
    - libXi.i686 
    - libXi.x86_64
    - libXtst.i686
    - libXtst.x86_64
    - make.x86_64
    - sysstat.x86_64
    - zip
    - unzip

# https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html
- name: Oracle 12c required groups
  group:
    name:  "{{ item }}"
    state: present
  loop:
    - "{{ oracle.groups.oinstall }}"
    - dba

- name: Oracle 12c required install account
  user:
    name: oracle
    group: "{{ oracle.groups.oinstall }}"
    groups: dba
  notify:
    - set-passord-oracle

- name: Oracle 12c environment variables bashrc file 
  template: 
    dest: /etc/profile.d/oracle.sh
    src: ../files/environment.exports.sh
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Oracle 12c kernel parameters
  copy:
    src: ../files/kernel.sysctl.conf
    dest: /etc/sysctl.d/oracle12c.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify:
    - apply-kernel-parameters

- name: Oracle 12c security limits
  copy:
    src: ../files/security.limits.conf
    dest: /etc/security/limits.d/oracle12c.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Oracle 12c install location
  file: 
    path: "{{ oracle.home }}"
    state: directory
    recurse: yes
    owner: oracle
    group: "{{ oracle.groups.oinstall }}"
    mode: u=rwx,g=rx,o=rx

# https://docs.ansible.com/ansible/latest/user_guide/playbooks_blocks.html
# https://docs.ansible.com/ansible/latest/modules/unarchive_module.html#unarchive-module
- name: Unpack Oracle media
  unarchive:
    src:        "{{ item.zip }}" 
    creates:    "{{ item.creates }}" 
    dest:       /tmp
    remote_src: yes
    owner: oracle
    group: "{{ oracle.groups.oinstall }}"
  loop:
    - { zip: '{{ oracle.media.zip1 }}', creates: '{{ oracle.media.installer }}/welcome.html' }
    - { zip: '{{ oracle.media.zip1 }}', creates: '{{ oracle.media.installer }}/stage/Components/oracle.ctx' }

- name: create oraInst.loc for silent installation
  template: 
    dest: /etc/oraInst.loc
    src: ../files/oraInst.loc
    owner: oracle
    group: "{{ oracle.groups.oinstall }}"
    mode: 644

- name: Create response file for silent installation
  template: 
    dest: "{{ oracle.media.installer }}/db_install.rsp"
    src: ../files/db_install.rsp
    owner: oracle
    group: "{{ oracle.groups.oinstall }}"
    mode: u=rw,g=r,o=r


#- name: Run the Oracle 12c installer
#  shell: /tmp/database/runInstaller -silent -responseFile /tmp/db_install.rsp 
#  args:
#    chdir: /tmp/database
#    creates: somelog.txt
#  become: true
#  become_user: oracle
