---
- name: Oracle 12c environment variables bashrc file
  template:
    src:   environment.exports.sh
    dest:  /etc/profile.d/oracle_server.sh
    owner: root
    group: root
    mode:  u=rw,g=r,o=r

- name: Oracle 12c kernel parameters /etc/sysctl.d/oracle12c.conf
  template:
    src:   kernel.sysctl.conf
    dest:  /etc/sysctl.d/oracle12c.conf
    owner: root
    group: root
    mode:  u=rw,g=r,o=r
  notify:
    - apply-kernel-parameters

- name: Oracle 12c security limits
  template:
    src:   security.limits.conf
    dest:  /etc/security/limits.d/oracle12c.conf
    owner: root
    group: root
    mode:  u=rw,g=r,o=r

# https://docs.ansible.com/ansible/latest/user_guide/playbooks_blocks.html
# https://docs.ansible.com/ansible/latest/modules/unarchive_module.html#unarchive-module
- name: Unpack Oracle media {{ oracle.media.zip1 }}
  unarchive:
    src:        "{{ oracle.media.zip1 }}"
    creates:    "{{ oracle.media.installer }}/welcome.html"
    dest:       /tmp
    remote_src: yes
    owner: "{{ oracle.user }}"
    group: "{{ oracle.groups.inventory }}"

- name: Unpack Oracle media {{ oracle.media.zip2 }}
  unarchive:
    src:        "{{ oracle.media.zip2 }}"
    creates:    "{{ oracle.media.installer }}/stage/Components/oracle.ctx"
    dest:       /tmp
    remote_src: yes
    owner: "{{ oracle.user }}"
    group: "{{ oracle.groups.inventory }}"
  when: oracle.media.zip2 is defined

- name: Create response file for silent installation - {{ oracle.media.installer }}/db_install.{{ oracle.version }}.rsp
  template:
    src:   db_install.{{ oracle.version }}.rsp
    dest:  "{{ oracle.media.installer }}/db_install.rsp"
    owner: "{{ oracle.user }}"
    group: "{{ oracle.groups.inventory }}"
    mode:  u=rw,g=r,o=r

- name: Run the Oracle 12c installer
  command: "{{ oracle.media.installer }}/runInstaller -silent -ignorePrereq -ignoreSysPrereqs -waitforcompletion -responseFile {{ oracle.media.installer }}/db_install.rsp"
  args:
    chdir:     "{{ oracle.media.installer }}"
    creates:   "{{ oracle.home }}/root.sh"
  become:      true
  become_user: "{{ oracle.user }}"

- name: Run the Oracle 12c post install root task
  shell: "{{ oracle.home }}/root.sh"
  args:
    creates: "/etc/oratab"
