---
- hosts: all
  become: true
  roles:
  - vagrant_localhost_fix
  - environment
  - basic

- hosts: database
  become: true
  roles:
  - oracle_common
  - oracle_server
  - oracle_server_listner
  - oracle_server_database

- hosts: documentum
  become: true
  roles:
  - random_generator
  - oracle_common
  - oracle_client
  - documentum_server
  - documentum_server_patch
  - documentum_server_fine_tuning
  - documentum_server_docbroker
  - documentum_server_docbroker_systemd
  - documentum_server_fine_tuning
  - documentum_server_repository
  - documentum_server_fine_tuning
  - documentum_server_repository_systemd
  - documentum_server_jms_systemd
