---

- hosts: documentum
  become: true
  roles:
#  - documentum_server_fine_tuning
#  - documentum_server_docbroker_systemd
#  - documentum_server_repository
#  - documentum_server_repository_systemd
#  - documentum_server_jms_systemd
  - documentum_administrator_on_jms
