---
- hosts: documentum
  become: true
  roles:
  - vagrant_localhost_fix
  - environment
  - basic

- hosts: documentum
  become: true
  roles:
  - random_generator
  - oracle_common
  - oracle_client
  - documentum_server
  - documentum_server_patch
  - documentum_administrator_on_jms
  - documentum_server_fine_tuning
  - documentum_server_systemd
  - documentum_server_docbroker
  - documentum_server_fine_tuning
  - documentum_server_repository
  - documentum_server_fine_tuning
