---

- hosts: database
  become: true
  roles:
  - vagrant_localhost_fix
  - environment
  - basic

- hosts: database
  become: true
  roles:
  - oracle_common
  - oracle_server
  - oracle_server_listner
  - oracle_server_database
