---
all:
  hosts:
    database:
    documentum:
    applications:
    ansible:
  vars:
    tmp_dir:       roles/tmp
    oracle:
      base:         /opt/oracle
      version:      12.1.0.2
      sid:          fgdb
      unqname:      fgdb
      gdbname:      fgdb.fg.ie
      home:         /opt/oracle/product/12.1.0.2/fgdb
      inventory:    /opt/oracle/oraInventory
      user:         oracle
      groups:
        inventory:  oinstall
        dba:        dba
      media:
        tmp:        /tmp
        installer:  /tmp/database
        zip1:       /media/software/Oracle/Database/linuxamd64_12102_database_1of2.zip
        zip2:       /media/software/Oracle/Database/linuxamd64_12102_database_2of2.zip
    oracle_database:
       data:        /opt/oracle/oradata/fgdb
    oracle_client:
      media:
        tmpdir:     /tmp
        installer:  /tmp/client
        zip:        /media/software/Oracle/Database/linuxamd64_12102_client.zip
    documentum_server:
      documentum:   /opt/documentum
      dctm_shared:  /opt/documentum/shared
      version:      16.4
      dm_home:      /opt/documentum/product/16.4
      user:         dmadmin
      uid:          5000
      group:        dmadmin
      gid:          5000 
      media:
        tmpdir:     /tmp/documentum_server
        zip:        /media/software/Documentum/D164/content_server_16.4_linux64_oracle.tar
      jms:
        port:       9090
        dir:        /opt/documentum/wildfly9.0.1/server/DctmServer_MethodServer
    documentum_server_patch:
      version:      16.4.0040.0057
      info:         /opt/documentum/patch/patch-info.xml
      java_home:    /opt/documentum/java64/1.8.0_152
      media:
        tmpdir:     /tmp/documentum_server_patch
        zip:        /media/software/Documentum/D164/CS_16.4.0040.0057_linux_ora_P04.tar.gz
        tar:        /tmp/documentum_server_patch/CS_16.4.0040.0057_linux_ora_P04.tar
        targz:      CS_16.4.0040.0057_linux_ora.tar.gz
    documentum_repository:
#      name:         farrengold
#      id:           2018123
      name:         harold
      id:           2018118
      port:         60010
      port_s:       60011

#
# https://github.com/ansible/ansible/blob/devel/examples/hosts.yaml
#
# This is the default ansible 'hosts' file.
#
# It should live in /etc/ansible/hosts
#
#   - Comments begin with the '#' character
#   - Blank lines are ignored
#   - Top level entries are assumed to be groups, start with 'all' to have a full hierarchy
#   - Hosts must be specified in a group's hosts:
#     and they must be a key (: terminated)
#   - groups can have children, hosts and vars keys
#   - Anything defined under a host is assumed to be a var
#   - You can enter hostnames or IP addresses
#   - A hostname/IP can be a member of multiple groups

# Ex 1: Ungrouped hosts, put them in 'all' or 'ungrouped' group
##all:
##  hosts:
##      green.example.com:
##          ansible_ssh_host: 191.168.100.32
##          anyvariable: value
##      blue.example.com:
##      192.168.100.1:
##      192.168.100.10:

# Ex 2: A collection of hosts belonging to the 'webservers' group
##  children:
##    webservers:
##      hosts:
##        alpha.example.org:
##        beta.example.org:
##        192.168.1.100:
##        192.168.1.110:

# Ex 3: You can create hosts using ranges and add children groups and vars to a group
# The child group can define anything you would normally add to a group

##    testing:
##      hosts:
##        www[001:006].example.com:
##      vars:
##        testing1: value1
##      children:
##        webservers:
##            hosts:
##                beta.example.org:

# Ex 4: all vars
# keeping within 'all' group you can define common 'all' vars here with lowest precedence

##  vars:
##      commontoall: thisvar