---
- hosts: all
  become: true
  roles:
  - vagrant_localhost_fix
  - environment
  - basic

- hosts: database
  become: true
  roles:
  - oracle_common
  - oracle_server
  - oracle_listner
  - oracle_database

- hosts: documentum
  become: true
  roles:
  - oracle_common
  - oracle_client
  - documentum_server
  - documentum_server_patch
  - documentum_server_fine_tuning
  - documentum_docbroker
  - documentum_server_fine_tuning
  - documentum_repository
  - documentum_server_fine_tuning
