---
- hosts: all
  become: true
  roles:
  - environment
  - basic

- hosts: database
  become: true
  roles:
  - oracle_server

- hosts: documentum
  become: true
  roles:
  - oracle_client
  - documentum_server
