---
- hosts: all
  become: true
  roles:
  - environment
  - basic

- hosts: database
  become: true
  roles:
  - oracle_common
  - oracle_server
  - oracle_listner

- hosts: documentum
  become: true
  roles:
  - oracle_common
  - oracle_client
  - documentum_server
  - documentum_server_patch
