---
- name: Documentum Repository Service file 
  template: 
    dest:   /etc/systemd/system/repository.service
    src:    repository.service
    owner:  root
    group:  root
    mode:   u=rwx,g=rx,o=rx

- name: Documentum Repository Service - start if not running
  systemd:
    name:          repository
    daemon_reload: yes
    enabled:       yes
    state:         started
