---
# https://docs.oracle.com/database/121/LACLI/pre_install.htm#LACLI1283


- name: Oracle 12c client environment variables bashrc file /etc/profile.d/oracle_client.sh 
  template: 
    dest:  /etc/profile.d/oracle_client.sh
    src:   environment.exports.sh
    owner: root
    group: root
    mode:  u=rw,g=r,o=r

- name: Unpack Oracle Client media {{ oracle_client.media.zip }}
  unarchive:
    src:        "{{ oracle_client.media.zip }}" 
    dest:       "{{ oracle_client.media.tmpdir }}"
    creates:    "{{ oracle_client.media.installer }}/runInstaller" 
    remote_src: yes
    owner:      "{{ oracle.user }}"
    group:      "{{ oracle.groups.inventory }}"

- name: Create response file for silent installation
  template: 
    dest:  "{{ oracle_client.media.installer  }}/client_install.rsp"
    src:   client_install.rsp
    owner: "{{ oracle.user }}"
    group: "{{ oracle.groups.inventory }}"
    mode:  u=rw,g=r,o=r

- name: Run the Oracle 12c Client installer
  command:     "{{ oracle_client.media.installer }}/runInstaller -silent -ignorePrereq -ignoreSysPrereqs -waitforcompletion -responseFile {{ oracle_client.media.installer  }}/client_install.rsp" 
  args:
    chdir:     "{{ oracle_client.media.installer }}"
    creates:   "{{ oracle.home }}/root.sh"
  become:      true
  become_user: "{{ oracle.user }}"
  register:     runInstaller

- debug: var=runInstaller.stdout_lines

- name: Run the Oracle 12c Client post install root task
  shell: "{{ oracle.home }}/root.sh"
#  args:
#    creates: "/etc/oratab"

# Here be dragons... flaky ... does depend on the fetch task in oracle_database having been executed
# https://stackoverflow.com/questions/48113332/ansible-how-to-copy-files-remote-to-remote?rq=1
- name: tnsnames.ora 
  copy:
    src:   "{{ roles_tmp }}/tnsnames.ora"
    dest:  "{{ oracle.home }}/network/admin/tnsnames.ora"
    owner: "{{ oracle.user }}"
    group: "{{ oracle.groups.inventory }}"
    mode:  u=rwx,g=rx,o=rx
    