---
# https://www.tecmint.com/install-oracle-database-12c-on-centos-7/
# https://valehagayev.wordpress.com/2016/09/08/oracle-12-1-0-2-silent-install-and-de-installation-on-oel/

- name: Oracle 12c required packages
  yum: 
    name:  "{{ packages }}"
  vars:
    packages:
    - binutils.x86_64
    - compat-libcap1.x86_64
    - gcc.x86_64
    - gcc-c++.x86_64
    - glibc.i686
    - glibc.x86_64
    - glibc-devel.i686
    - glibc-devel.x86_64
    - ksh
    - compat-libstdc++-33
    - libaio.i686
    - libaio.x86_64
    - libaio-devel.i686
    - libaio-devel.x86_64
    - libgcc.i686
    - libgcc.x86_64
    - libstdc++.i686
    - libstdc++.x86_64
    - libstdc++-devel.i686
    - libstdc++-devel.x86_64
    - libXi.i686 
    - libXi.x86_64
    - libXtst.i686
    - libXtst.x86_64
    - make.x86_64
    - sysstat.x86_64
    - zip
    - unzip

# https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html
- name: Oracle 12c required groups
  group:
    name:  "{{ item }}"
    state: present
  loop:
    - oinstall
    - dba

- name: Oracle 12c required install account
  user:
    name: oracle
    group: oinstall
    groups: dba
  notify:
    - set-passord-oracle
    
- name: Report Oracle 12c home
  debug:
    msg: "Oracle Home: {{ oracle_home }}"

- name: Oracle 12c environment variables bashrc file 
  template: 
    dest: /etc/profile.d/oracle.sh
    src: ../files/environment.exports.sh
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Oracle 12c kernel parameters
  copy:
    src: ../files/kernel.sysctl.conf
    dest: /etc/sysctl.d/oracle12c.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify:
    - apply-kernel-parameters

- name: Oracle 12c security limits
  copy:
    src: ../files/security.limits.conf
    dest: /etc/security/limits.d/oracle12c.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Oracle 12c install location
  file: 
    path: "{{ oracle_home }}"
    state: directory
    recurse: yes
    owner: oracle
    group: oinstall
    mode: u=rwx,g=rx,o=rx
