---
# https://docs.ansible.com/ansible/latest/modules/yum_module.html
- name: ensure a list of packages installed
  yum: 
    name:  "{{ packages }}"
  vars:
    packages:
    - git

- name: Create account for myself
  user:
    name: brian
  notify:
    - set-password-brian

# https://docs.ansible.com/ansible/latest/modules/copy_module.html#copy-module
- name: Add date and time to prompt
  copy:
    src: ../files/time_prompt.sh
    dest: /etc/profile.d/time_prompt.sh
    owner: root
    group: root
    mode: u=rw,g=r,o=r
