---
- name: Documentum Server required packages
  yum: 
    name:  "{{ packages }}"
  vars:
    packages:
    - expect
    - tcl

- name: Documentum Server group
  group:
    name:  "{{ documentum_server.group }}"
    gid:   "{{ documentum_server.gid }}"
    state: present

- name: Documentum server required install account
  user:
    name:  "{{ documentum_server.user }}"
    group: "{{ documentum_server.group }}"
    groups: 
       - "{{ oracle.groups.dba }}"
       - "{{ oracle.groups.inventory }}"
  notify:
    - set-passord-documentum

- name: Documentum Server install location
  file: 
    path:     "{{ item }}"
    state:    directory
    recurse:  no
    owner:    "{{ documentum_server.user }}"
    group:    "{{ documentum_server.group }}"
    mode:     u=rwx,g=rx,o=rx
  loop:
    - "{{ documentum_server.documentum }}"
    - "{{ documentum_server.dctm_shared }}"
    - "{{ documentum_server.media.tmpdir }}"

- name: Documentum Server pre-installation tasks for Red Hat Enterprise Linux
  file: 
    path:  /usr/lib64/libsasl2.so.2
    src:   /usr/lib64/libsasl2.so.3.0.0 
    state: link

- name: Documentum environment variables bashrc file 
  template: 
    dest:   /etc/profile.d/documentum_server.sh
    src:    ../files/environment.exports.sh
    owner:  root
    group:  root
    mode:   u=rw,g=r,o=r

- name: Documentum Server security limits
  copy:
    src:    ../files/security.limits.conf
    dest:   /etc/security/limits.d/documentum_server.conf
    owner:  root
    group:  root
    mode:   u=rw,g=r,o=r

- name: Unpack Documentum Server media
  unarchive:
    src:        "{{ documentum_server.media.zip }}" 
    dest:       "{{ documentum_server.media.tmpdir }}"
    creates:    "{{ documentum_server.media.tmpdir }}/serverSetup.bin" 
    remote_src: yes
    owner:      "{{ documentum_server.user }}"
    group:      "{{ documentum_server.group }}"

- name: Setup script to install Documentum Server software 
  template: 
    dest:   "{{ documentum_server.media.tmpdir }}/serverSetup.sh"
    src:    ../files/serverSetup.sh
    owner:  "{{ documentum_server.user }}"
    group:  "{{ documentum_server.group }}"
    mode:   u=rwx,g=r,o=r

- name: Install Documentum Server software
  shell:        "{{ documentum_server.media.tmpdir }}/serverSetup.sh"
  become:       true
  become_user:  dmadmin
  args:
    executable: /bin/bash
    chdir:      "{{ documentum_server.media.tmpdir }}"
    creates:    "{{ documentum_server.dm_home }}/version.txt"