---
- name: Add etc/services entries for Documentum Repository {{ documentum_repository.name}}
  lineinfile:
    path:  /etc/services
    line:  "{{ item }}"
  loop:
    - "{{ documentum_repository.name}}      {{ documentum_repository.port}}/tcp               # Documentum Repository {{ documentum_repository.name}}"
    - "{{ documentum_repository.name}}_s    {{ documentum_repository.port_s}}/tcp             # Documentum Repository {{ documentum_repository.name}} Secure"

- name: Create Documentum Repository response file
  template:
    dest:   "{{ documentum_server.documentum }}/config.repository.{{ documentum_repository.name}}.properties"
    src:    linux_config.properties
    owner:  "{{ documentum_server.user }}"
    group:  "{{ documentum_server.group }}"
    mode:   u=rw,g=r,o=r

- name: Create Repository
  shell:        "{{ documentum_server.dm_home }}/install/dm_launch_server_config_program.sh -f {{ documentum_server.documentum }}/config.repository.{{ documentum_repository.name}}.properties -r {{ documentum_server.documentum }}/response.repository.{{ documentum_repository.name}}.properties -i Silent -DLOG_LEVEL=DEBUG -DKEEP_TEMP_FILE=true"
  become:       true
  become_user:  "{{ documentum_server.user }}"
  args:
    executable: /bin/bash
    chdir:      "{{ documentum_server.dm_home }}/install"
    creates:    "{{ documentum_server.documentum }}/dba/dm_start_{{ documentum_repository.name}}"
  register:     repository
  environment:
    DOCUMENTUM:  "{{ documentum_server.documentum }}"
    DM_HOME:     "{{ documentum_server.dm_home }}"
    DOCUMENTUM_SHARED: "{{ documentum_server.dctm_shared }}"
    ORACLE_HOME: "{{ oracle.home }}"
    ORACLE_SID:  "{{ oracle.sid }}"

- debug: var=repository.stdout_lines

- name: Repository server.ini - disable IP V6
  lineinfile:
    line:    "ip_mode = V4ONLY"
    path:    "{{ documentum_server.documentum }}/dba/config/{{ documentum_repository.name}}/server.ini"
    state:   present
    insertafter: "enforce_four_digit_year = T"

- name: Stop Repository after first creation - reconfigure server.ini and let systemd take ownership
  shell:        "{{ documentum_server.documentum }}/dba/dm_shutdown_{{ documentum_repository.name}}"
  become:       true
  become_user:  "{{ documentum_server.user }}"
  args:
    executable: /bin/bash
    chdir:      "{{ documentum_server.dm_home }}"
  environment:
    DOCUMENTUM:  "{{ documentum_server.documentum }}"
    DM_HOME:     "{{ documentum_server.dm_home }}"
    DOCUMENTUM_SHARED: "{{ documentum_server.dctm_shared }}"
    ORACLE_HOME: "{{ oracle.home }}"
    ORACLE_SID:  "{{ oracle.sid }}"
  when: repository is changed

- name: Documentum Repository Service - start if not running
  systemd:
    name:          documentum-repository
    state:         started

- name: Documentum JMS Service - start if not running
  systemd:
    name:          documentum-jms
    state:         started
