---
- name: Create response file for silent installation
  template: 
    dest:  "{{ oracle.media.installer }}/dbca.rsp"
    src:   dbca.rsp
    owner: "{{ oracle.user }}"
    group: "{{ oracle.groups.inventory }}"
    mode:  u=rw,g=r,o=r

- name: Create Oracle Database {{ oracle.sid }} in {{ oracle_database.data }}
  command:     "{{ oracle.home }}/bin/dbca -silent -responseFile {{ oracle.media.installer }}/dbca.rsp"
  become:       true
  become_user:  "{{ oracle.user }}"
  args:
    creates:    "{{ oracle_database.data }}"

- name: Copy server tnsames.ora to local for later use on Documentum servers
  fetch: 
    dest:  "{{ tmp_dir }}/tnsnames.ora"
    src:   "{{ oracle.home }}/network/admin/tnsnames.ora"
    flat: yes

- name: /etc/oratab - remove default setting to not start on host start up
  lineinfile:
    line:    "{{ oracle.sid}}:{{ oracle.home }}:N"
    path:    /etc/oratab
    state:   absent

- name: /etc/oratab - Set database to start on host start up
  lineinfile:
    line:    "{{ oracle.sid}}:{{ oracle.home }}:Y"
    path:    /etc/oratab

- name: Oracle dbora Service file 
  template: 
    dest:   /etc/systemd/system/dbora.service
    src:    dbora.service
    owner:  root
    group:  root
    mode:   u=rwx,g=rx,o=rx

- name: Enable the dbora service, also issue daemon-reload to pick up config changes
  systemd:
    name:          dbora
    daemon_reload: yes
    enabled:       yes
