---
#- name: copy listener response file
#  template: src=netca.rsp dest={{ oracle.home }}/netca.rsp

- name: Create default listener using netca
  command:      "{{ oracle.home }}/bin/netca -silent -responseFile {{ oracle.home }}/assistants/netca/netca.rsp"
  args:
    creates:    "{{ oracle.home }}/network/admin/listener.ora"
  become:       true
  become_user:  "{{ oracle.user }}"

# https://docs.oracle.com/cd/B19306_01/install.102/b15660/app_port.htm
- name: Open firewall - Oracle listner
  firewalld:
    port:      1521/tcp
    permanent: true
    state:     enabled
    immediate: yes
