---
#- name: copy listener response file
#  template: src=netca.rsp dest={{ oracle.home }}/netca.rsp

- name: Create default listener using netca
  command:      "{{ oracle.home }}/bin/netca -silent -responseFile {{ oracle.home }}/assistants/netca/netca.rsp"
  creates:      "{{ oracle.home }}/network/admin/listener.ora"  
  become:       true
  become_user:  oracle
