---
- name: Documentum JMS Service file
  template:
    dest:   /etc/systemd/system/jms.service
    src:    jms.service
    owner:  root
    group:  root
    mode:   u=rwx,g=rx,o=rx

- name: Documentum Server JMS Service - enable and start if not running
  systemd:
    name:          jms
    daemon_reload: yes
    enabled:       yes
# It does not start within JBoss stability timeout.
# But no problem on system reboot, hence will let an OS reboot solve this!!
